### ISSUE TITLE
哔哩哔哩

### ISSUE THREAD

**Issue by wuge0** [sanshuifeibing/ExampleForSCF#10]
复制哔哩哔哩的Cookie不行啊。
请问是哪段Cookie才可以啊？

**Comment by YYplus** [comment]
需要删掉内容留下会用到的就好了

**Comment by wuge0** [comment]
帮忙看看需要删除哪段
cookie: CURRENT_FNVAL=16; rpdid=|(~J)u|mYk|0J'ulm~m~lklR; sid=c46edd07; DedeUserID=15222693; DedeUserID__ckMd5=d47806988b971fff; SESSDATA=841ef177%2C1614055178%2Cfc31d*81; bili_jct=bac0aa36af97b4f263461931b6b46041; _uuid=5E90CABF-9754-0B84-250A-BAC100FFD04C41397infoc; buvid3=3ADBFDF8-9B2E-4370-9D4B-5C59009AC247143109infoc; blackside_state=1; bfe_id=1bad38f44e358ca77469025e0405c4a6

**Comment by YYplus** [comment]
sid=c46edd07; DedeUserID__ckMd5=d47806988b971fff; SESSDATA=841ef177%2C1614055178%2Cfc31d*81; bili_jct=bac0aa36af97b4f263461931b6b46041;
把这个直接复制进去试试

**Comment by wuge0** [comment]
谢谢，我试了，可以的
