### ISSUE TITLE
52破解的cookie

### ISSUE THREAD

**Issue by behappy00** [sanshuifeibing/ExampleForSCF#14]
这个我找不到，同谷歌浏览器，然后F12，network，不显示cookie啊，求图片指导

**Comment by misaka-h** [comment]
我个人的理解：
![第一步](https://img.imgdb.cn/item/5ff86aee3ffa7d37b350957d.png)
![第二步](https://img.imgdb.cn/item/5ff86aee3ffa7d37b350957f.png)

**Comment by lkyu-ly** [comment]
- 1 ![1](https://img.imgdb.cn/item/5ff86d543ffa7d37b352212c.png)
- 2 ![2](https://img.imgdb.cn/item/5ff86d543ffa7d37b352212a.png)
