### ISSUE TITLE
腾讯云函数同样失败

### ISSUE THREAD

**Issue by 1462903025** [sanshuifeibing/ExampleForSCF#16]
报错如下

START RequestId:aa2f298c-d392-4a1e-9e11-f2956b6e046b

ERROR RequestId:aa2f298c-d392-4a1e-9e11-f2956b6e046b Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 674, in exec_module\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 781, in get_code\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 741, in source_to_code\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 10\n    requests.session().get(\"https://sc.ftqq.com/SCU158181Td1a9de8b37280502ec149541b2c7d59a601bc0508f3d0.send?text=\" + info + \"\u0026desp=\" + specific,headers=headers)\n    ^\nIndentationError: unexpected indent","statusCode":443}

END RequestId:aa2f298c-d392-4a1e-9e11-f2956b6e046b

Report RequestId:aa2f298c-d392-4a1e-9e11-f2956b6e046b Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by 1gcat** [comment]
检查一下环境，我这测试正常
