### ISSUE TITLE
吾爱签到失效了

### ISSUE THREAD

**Issue by Phoebus888** [sanshuifeibing/ExampleForSCF#17]
吾爱签到失效了

**Comment by 9850RH** [comment]
同失效
Starting new HTTPS connection (1): www.52pojie.cn:443
https://www.52pojie.cn:443 "GET /home.php?mod=task&do=draw&id=2 HTTP/1.1" 403 None

{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"5d2e069f-65fb-4900-8e1d-d68bcd5d1d43","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 21, in main\n    c=b.find('div',id='messagetext').find('p').text\nAttributeError: 'NoneType' object has no attribute 'find'","statusCode":430}

访问https://www.52pojie.cn/home.php?mod=task&do=draw&id=2 显示“不是进行中的任务”

**Comment by 1gcat** [comment]
> 同失效
> Starting new HTTPS connection (1): [www.52pojie.cn:443](http://www.52pojie.cn:443)
> https://www.52pojie.cn:443 "GET /home.php?mod=task&do=draw&id=2 HTTP/1.1" 403 None
> 
> {"errorCode":-1,"errorMessage":"user code exception caught","requestId":"5d2e069f-65fb-4900-8e1d-d68bcd5d1d43","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 21, in main\n c=b.find('div',id='messagetext').find('p').text\nAttributeError: 'NoneType' object has no attribute 'find'","statusCode":430}
> 
> 访问https://www.52pojie.cn/home.php?mod=task&do=draw&id=2 显示“不是进行中的任务”

可以加个循环重复签到一两次解决。不知道什么原因，我这偶尔也这样，但大部分时间正常。
