### ISSUE TITLE
哔哩哔哩观看视频失败了

### ISSUE THREAD

**Issue by wudicyg** [sanshuifeibing/ExampleForSCF#18]
我更换了BV号之后依旧是失败的，直播签到是成功的

下面是请求日志部分内容：

https://api.bilibili.com:443 "GET /x/web-interface/view?bvid=BV1ty4y1u7w4 HTTP/1.1" 200 None

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "GET /x/web-interface/view?aid=803565321 HTTP/1.1" 200 None

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "POST /x/report/click/h5 HTTP/1.1" 200 38

av803565321观看失败 <Response [200]>

Starting new HTTPS connection (1): sc.ftqq.com:443

**Comment by 1gcat** [comment]
已更新。
