### ISSUE TITLE
请指导

### ISSUE THREAD

**Issue by yinghuo666** [sanshuifeibing/ExampleForSCF#2]
执行失败
_uuid=72D815AF-0E4D-091B-EA92-EFF7F20DD4F178379infoc; buvid3=2A01C736-2DB8-4B26-92E7-9276D848B28270389infoc; sid=ctkb256y; DedeUserID=345265463; DedeUserID__ckMd5=bc839148aad38052; SESSDATA=5eb2bf2f%2C1611033994%2Cae3e4*71; bili_jct=b0a8fae0eb980d3485630cfcb1e7e5d0; bp_t_offset_345265463=415060257896950709; CURRENT_FNVAL=16; rpdid=|(J~R~k)mmkJ0J'ulmlR)k|kl; PVID=1; bp_video_offset_345265463=415534714339115513; finger=1777945899

![N0FH9$X405TN6ARD)CE Z{C](https://user-images.githubusercontent.com/45911927/88481699-7cd79e80-cf8f-11ea-870b-ee656f7fc014.png)
![image](https://user-images.githubusercontent.com/45911927/88481713-97117c80-cf8f-11ea-8e02-083eeb51fdc1.png)

**Comment by 1gcat** [comment]
看一下报错。

**Comment by yinghuo666** [comment]
直接报错没有日志输出

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："三水非冰 "<notifications@github.com&gt;;
发送时间：2020年7月27日(星期一) 中午11:51
收件人："sanshuifeibing/ExampleForSCF" <ExampleForSCF@noreply.github.com&gt;;
抄送："yinghuo666 "<311707001220@home.hpu.edu.cn&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [sanshuifeibing/ExampleForSCF] 请指导 (#2)
-----------------------------------

 

 
看一下报错。

**Comment by 1gcat** [comment]
那你本地测试一下，一般本地没问题scf也没问题的。

**Comment by SunAo-Oct** [comment]
执行方法设置为index.main 
这个设置对了没  我开始就这个设置错了

**Comment by YYplus** [comment]
把cookie里多余的参数删除可能会解决问题
