### ISSUE TITLE
拿不到cookie

### ISSUE THREAD

**Issue by YYplus** [sanshuifeibing/ExampleForSCF#3]
可以说一下这两个的cookie咋找吗

**Comment by 1gcat** [comment]
浏览器按F12，在Network处可以找到。

**Comment by YYplus** [comment]
找到了但不知道对不对
![AC0(SW99OPHNFD9{{ZB)QVL](https://user-images.githubusercontent.com/65841378/89649662-aa3a1b80-d8b0-11ea-9123-b541ed0bcf92.png)

**Comment by jiujiwuan** [comment]
> 找到了但不知道对不对
> ![AC0(SW99OPHNFD9{{ZB)QVL](https://user-images.githubusercontent.com/65841378/89649662-aa3a1b80-d8b0-11ea-9123-b541ed0bcf92.png)
朋友你好，请问你这个是用哪个浏览器找到的呀？我试了好多，比如火狐，谷歌，ie，115，最后用的星愿浏览器貌似找到了，但是我也不知道对不对。
