### ISSUE TITLE
老哥可否弄一个详细的教程呀？

### ISSUE THREAD

**Issue by jiujiwuan** [sanshuifeibing/ExampleForSCF#4]
如题，首先能有代码就很不错了，但是我们大家都是小白，对这些东西相当于门外汉--一窍不通，根本不知道怎么操作，而如果是专业的，我想也就不需要看别人的教程了。
所以特别希望能够有一个更加详细的教程，比如怎么获取cookie，这几乎是最关键的步骤了，一笔带过或者避而不谈的话往往会提高门槛。

**Comment by YYplus** [comment]
我用的谷歌浏览器，按F12打开控制台，切换到network，这时候要刷新一次网页，r然后找到cookie,全部复制就可以，有其他问题的话继续提
