### ISSUE TITLE
哔哩哔哩签到失败 此消息没有正文

### ISSUE THREAD

**Issue by wy1ng** [sanshuifeibing/ExampleForSCF#7]
START RequestId: 550b7d7a-4aa0-45f3-831d-d72f2c372342

Event RequestId: 550b7d7a-4aa0-45f3-831d-d72f2c372342

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "GET /x/space/myinfo HTTP/1.1" 200 49

登录失败：账号未登录

Starting new HTTPS connection (1): sc.ftqq.com:443

https://sc.ftqq.com:443 "GET /SCU103261T8fc748a7dc24f7badc6c798bc34e0f815efa8ad2eb84a.send?text=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AD%BE%E5%88%B0%E5%A4%B1%E8%B4%A5&desp= HTTP/1.1" 200 None

 

END RequestId: 550b7d7a-4aa0-45f3-831d-d72f2c372342

Report RequestId: 550b7d7a-4aa0-45f3-831d-d72f2c372342 Duration:281ms Memory:64MB MemUsage:24.316406MB

求助，cookie是在home里找吗，感觉不对。。。

**Comment by KeyOfSky** [comment]
https://blog.csdn.net/fengda2870/article/details/84790323   登录B站前按F12，再登陆，获取cookie。如果cookie有单引号则外面改为双引号cookies = “你的cookie”
